### ISSUE TITLE
欢迎访问此博客(敏毅)!

### ISSUE THREAD

**Issue by LeslieZhu** [LeslieZhu/MinYi#1]
# 博客：敏毅

『士不可以不弘毅，任重而道远!』

## 介绍

毕业后，在北京工作四年，风尘仆仆；如今来到西安，客居在曾经向往的地方，让一切都重新开始。

在2015结束之前，一直通过 [敏毅](http://lesliezhu.github.com/) 来写博客，还为此写了个一个程序[OrgNote](https://github.com/LeslieZhu/OrgNote)来方便自己管理博客；后来，慢慢觉得还是`GitHub Issues`简单方便，就开始改到这里，但至今也没有写太多东西。

现在，将2015年以前的做一个集合，同时以后通过`GitHub Issues`准备做下列事情：

- **翻译文章**：包括英文翻译、日文翻译、中文翻译等等，尽量而为
- **技术博客**：平时学习、工作中遇到的问题，总结为笔记，保存下来
- **长安遍地是黄金**： 一些鸡毛蒜皮的事情，放到这里来，做个记录

一般会每周新建一个里程碑，然后将上周建的issues关闭，我特意整理了一个归档来查看所有博文:

- **[敏毅-归档](https://github.com/LeslieZhu/MinYi)**

## 留言、评论

可以直接在Issue下面提交评论，或者新建一个issue进行留言、评论。

## QQ讨论群（215909597）: `Pythoner@西安`  

![pythoner](https://cloud.githubusercontent.com/assets/2840435/11452481/ceac1704-9623-11e5-9cd8-f5edb5747812.png)

## 工作机会

本人科班出身，有一定的计算机编程能力，对于Python编程语言比较熟悉，对于Linux维护和Shell脚本编程也有一定的经验，其它各种计算机技术也有所涉猎。如果有兼职或者全职的相关工作机会，可以通过QQ联系我。

另外，本人身体壮实，也能干体力活，如有送快递、扛大包的活也可以联系我；四海为家，广交朋友，打个照面也是缘分。

## 版权说明

未经允许，禁止转载！

**Comment by orangle** [comment]
这是看到的第二个类似博客
